apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: lcc-system
spec:
  containers:
  - name: dnsutils
    image: registry.cn-hangzhou.aliyuncs.com/lcc-middleware/jessie-dnsutils:1.3
    command:
      - sleep
      - "360000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
